### ISSUE TITLE
IndexOutOfError in getPositionForSection

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/CustomFastScrollViewDemo#1]
<blockquote>
The bug appears when scrolling to the button of the list, and then and an IndexOutofError exception occurs when getPositionForSection is called. The index is always 1 larger than the total number of sections. So I think the code to calculate which section to return may be off by one but I’m not sure where to fix it.
I’m not sure why its only occurring for one of my data files. For all the others its working fine.
</blockquote>

**Comment by bilal703** [comment]
Hi here's the stack output:

01-18 13:54:10.924: E/InputEventReceiver(11143): Exception dispatching input event.
01-18 13:54:10.924: D/AndroidRuntime(11143): Shutting down VM
01-18 13:54:10.924: W/dalvikvm(11143): threadid=1: thread exiting with uncaught exception (group=0x41365930)
01-18 13:54:10.934: E/AndroidRuntime(11143): FATAL EXCEPTION: main
01-18 13:54:10.934: E/AndroidRuntime(11143): java.lang.IndexOutOfBoundsException: Invalid index 26, size is 26
01-18 13:54:10.934: E/AndroidRuntime(11143):    at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:251)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at java.util.ArrayList.get(ArrayList.java:304)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at com.iagrams.widget.SeparatedListAdapter$1.getPositionForSection(SeparatedListAdapter.java:286)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at com.iagrams.widget.SeparatedListAdapter.getPositionForSection(SeparatedListAdapter.java:225)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at android.widget.FastScroller.getThumbPositionForListPosition(FastScroller.java:649)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at android.widget.FastScroller.onScroll(FastScroller.java:457)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at android.widget.AbsListView.invokeOnItemScrollListener(AbsListView.java:1337)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at android.widget.AbsListView.trackMotionScroll(AbsListView.java:4949)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at android.widget.AbsListView.scrollIfNeeded(AbsListView.java:3087)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at android.widget.AbsListView.startScrollIfNeeded(AbsListView.java:3032)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at android.widget.AbsListView.onTouchEvent(AbsListView.java:3357)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at android.view.View.dispatchTouchEvent(View.java:7239)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2168)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1903)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1953)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1405)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at android.app.Activity.dispatchTouchEvent(Activity.java:2410)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1901)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at android.view.View.dispatchPointerEvent(View.java:7419)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3220)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3165)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4292)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4271)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4363)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:179)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:171)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:4342)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:4382)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at android.view.Choreographer.doCallbacks(Choreographer.java:562)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at android.view.Choreographer.doFrame(Choreographer.java:530)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at android.os.Handler.handleCallback(Handler.java:725)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at android.os.Handler.dispatchMessage(Handler.java:92)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at android.os.Looper.loop(Looper.java:137)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at android.app.ActivityThread.main(ActivityThread.java:5039)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at java.lang.reflect.Method.invokeNative(Native Method)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at java.lang.reflect.Method.invoke(Method.java:511)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
01-18 13:54:10.934: E/AndroidRuntime(11143):    at dalvik.system.NativeStart.main(Native Method)
01-18 13:54:10.974: D/dalvikvm(11143): GC_CONCURRENT freed 267K, 8% free 10260K/11052K, paused 3ms+2ms, total 37ms

It does n't happen for any other data file apart from one. I have sections A-Z (26 sections) so the index should never be 26.

Thanks.
